(function(g){var window=this;var iqa=function(a,b){return g.Ub(a,b)},W5=function(){},jqa=function(a){if(a.Bc&&"function"==typeof a.Bc)return a.Bc();
if(g.Da(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},kqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.Da(a))(0,g.y)(a,b,void 0);else{if(a.Od&&"function"==typeof a.Od)var c=a.Od();else if(a.Bc&&"function"==typeof a.Bc)c=void 0;else if(g.La(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=jqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},X5=function(a){g.sn(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},Y5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.xn(a.l,b,c)},Z5=function(a){return(a=g.Qo(a))?new ActiveXObject(a):new XMLHttpRequest},$5=function(a,b){return b+" ["+a.Y+" "+a.D+" "+a.getStatus()+"]"},lqa=function(a){return"content-type"==a.toLowerCase()},a6=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.u.clearTimeout(a.F),a.F=null)},mqa=function(a){return g.Ld&&g.ld(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},b6=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},c6=function(a,b){if(a.g){a6(a);
var c=a.g,d=a.P[0]?g.Ha:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},d6=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;b6(a);c6(a)},e6=function(a){return a.g?a.g.readyState:0},f6=function(a){if(a.i&&"undefined"!=typeof g.UY)if(a.P[1]&&4==e6(a)&&2==a.getStatus())$5(a,"Local request error detected and ignored");
else if(a.B&&4==e6(a))g.Gg(a.qw,0,a);else if(a.dispatchEvent("readystatechange"),4==e6(a)){$5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!nqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<e6(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";b6(a)}}finally{c6(a)}}},g6=function(a){g.Qf.call(this);
this.headers=new g.gn;this.N=a||null;this.i=!1;this.P=this.g=null;this.Y=this.D="";this.u=0;this.l="";this.o=this.aa=this.B=this.R=!1;this.A=0;this.F=null;this.X="";this.I=this.T=!1},h6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},oqa=function(a,b){var c=[];
g.Rk(b,function(d){try{var e=g.ep.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.dp(e)&&c.push(d):c.push(d)},a);
return c},pqa=function(a,b){var c=oqa(a,b);
(0,g.y)(c,function(d){g.ep.prototype.remove.call(this,d)},a)},i6=function(a){if(a.gd){if(a.gd.locationOverrideToken)return{locationOverrideToken:a.gd.locationOverrideToken};
if(null!=a.gd.latitudeE7&&null!=a.gd.longitudeE7)return{latitudeE7:a.gd.latitudeE7,longitudeE7:a.gd.longitudeE7}}return null},qqa=function(a,b){g.$a(a,b)||a.push(b)},j6=function(a){var b=0,c;
for(c in a)b++;return b},k6=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},rqa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},sqa=function(a,b,c,d){var e=new g.kn(null,void 0);
a&&g.ln(e,a);b&&g.mn(e,b);c&&g.nn(e,c);d&&(e.i=d);return e},l6=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return rqa(a)},m6=function(){this.g=[];
this.i=[]},n6=function(a,b){g.jq[a]=!0;
var c=g.hq();c&&c.publish.apply(c,arguments);g.jq[a]=!1},o6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.gn;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",tqa(this,a.capabilities||""),uqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},tqa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(iqa,vqa)).forEach(function(c){a.capabilities.add(c)})},uqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},p6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},q6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},r6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},wqa=function(a){return new p6(a)},s6=function(a){return g.Ka(a)?(0,g.ge)(a,wqa):[]},t6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},u6=function(a){return g.Ka(a)?"["+(0,g.ge)(a,t6).join(",")+"]":"null"},v6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},xqa=function(a){return(0,g.ge)(a,function(b){return{key:b.id,
name:b.name}})},w6=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},x6=function(a,b){return g.Xa(a,function(c){return q6(c,b)})},y6=function(a){try{var b=(0,g.Ft)(),c=(0,g.Et)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},yqa=function(){var a=(0,g.Et)();
a&&pqa(a,a.g.mf(!0))},z6=function(){var a=g.Ht("yt-remote-connected-devices")||[];
g.qb(a);return a},zqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ge)(a,function(d,e){return 0==e?d:d.substring(c.length)})},A6=function(a){g.Gt("yt-remote-connected-devices",a,86400)},C6=function(){if(B6)return B6;
var a=g.Ht("yt-remote-device-id");a||(a=v6(),g.Gt("yt-remote-device-id",a,31536E3));for(var b=z6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return B6=d},D6=function(){var a=z6(),b=C6();
g.$a(a,b);g.It()&&g.sb(a,b);a=zqa(a);if(0==a.length)try{g.Js("remote_sid")}catch(c){}else try{g.Is("remote_sid",a.join(","),-1)}catch(c){}},E6=function(){return g.Ht("yt-remote-session-browser-channel")},F6=function(){return g.Ht("yt-remote-local-screens")||[]},G6=function(){g.Gt("yt-remote-lounge-token-expiration",!0,86400)},Aqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ge)(F6(),function(d){return d.loungeToken}),c=(0,g.ge)(a,function(d){return d.loungeToken});
(0,g.mj)(c,function(d){return!g.$a(b,d)})&&G6();
g.Gt("yt-remote-local-screens",a,31536E3)},Bqa=function(a,b){g.Gt("yt-remote-session-browser-channel",a);
g.Gt("yt-remote-session-screen-id",b);var c=z6(),d=C6();g.$a(c,d)||c.push(d);A6(c);D6()},H6=function(a){a||(y6("yt-remote-session-screen-id"),y6("yt-remote-session-video-id"));
D6();a=z6();g.db(a,C6());A6(a)},J6=function(){if(!I6){var a=g.op();
a&&(I6=new g.Zo(a))}return I6?!!I6.get("yt-remote-use-staging-server"):!1},K6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},L6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},N6=function(a){a.length?M6(a.shift(),function(){N6(a)}):O6()},Cqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},M6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},O6=function(){var a=L6();
a&&a(!1,"No cast extension found")},P6=function(){if(Dqa){var a=2,b=L6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;M6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",O6,c)}},Eqa=function(){P6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);N6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},Q6=function(a,b,c){g.A.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Zc=b;this.u=(0,g.x)(this.yD,this);this.g=!1;this.i=0;this.l=this.Aa=null;this.o=[]},R6=function(){},S6=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ca=new g.yn(this);this.i=new g.Fg;this.i.setInterval(250)},U6=function(a,b,c){a.Yh=1;
a.ag=X5(b.clone());a.sh=c;a.u=!0;T6(a,null)},V6=function(a,b,c,d,e){a.Yh=1;
a.ag=X5(b.clone());a.sh=null;a.u=c;e&&(a.iA=!1);T6(a,d)},T6=function(a,b){a.Hi=(0,g.D)();
W6(a);a.Eg=a.ag.clone();Y5(a.Eg,"t",a.A);a.nl=0;a.wc=a.g.Hp(a.g.Wk()?b:null);0<a.mq&&(a.Zn=new g.Jl((0,g.x)(a.oB,a,a.wc),a.mq));a.ca.da(a.wc,"readystatechange",a.oM);var c=a.Zg?g.bc(a.Zg):{};a.sh?(a.Go="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.wc.send(a.Eg,a.Go,a.sh,c)):(a.Go="GET",a.iA&&!g.Nd&&(c.Connection="close"),a.wc.send(a.Eg,a.Go,null,c));a.g.ze(1)},c7=function(a,b,c){for(var d=!0;!a.Og&&a.nl<c.length;){var e=Fqa(a,c);
if(e==X6){4==b&&(a.rg=4,Y6(15),d=!1);break}else if(e==Z6){a.rg=4;Y6(16);d=!1;break}else $6(a,e)}4==b&&0==c.length&&(a.rg=1,Y6(17),d=!1);a.Ce=a.Ce&&d;d||(a7(a),b7(a))},Fqa=function(a,b){var c=a.nl,d=b.indexOf("\n",c);
if(-1==d)return X6;c=Number(b.substring(c,d));if(isNaN(c))return Z6;d+=1;if(d+c>b.length)return X6;var e=b.substr(d,c);a.nl=d+c;return e},f7=function(a,b){a.Hi=(0,g.D)();
W6(a);var c=b?window.location.hostname:"";a.Eg=a.ag.clone();g.sn(a.Eg,"DOMAIN",c);g.sn(a.Eg,"t",a.A);try{a.Ge=new ActiveXObject("htmlfile")}catch(n){a7(a);a.rg=7;Y6(22);b7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in d7)k=d7[l];else if(l in e7)k=d7[l]=e7[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
d7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.Ge.open();a.Ge.write(g.Mc(c));a.Ge.close();a.Ge.parentWindow.m=(0,g.x)(a.DL,a);a.Ge.parentWindow.d=(0,g.x)(a.oz,a,!0);a.Ge.parentWindow.rpcClose=(0,g.x)(a.oz,a,!1);c=a.Ge.createElement("DIV");a.Ge.parentWindow.document.body.appendChild(c);d=g.Cc(a.Eg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.ze(1)},W6=function(a){a.xt=(0,g.D)()+a.o;
g7(a,a.o)},g7=function(a,b){if(null!=a.aj)throw Error("WatchDog timer not null");
a.aj=h7((0,g.x)(a.NL,a),b)},i7=function(a){a.aj&&(g.u.clearTimeout(a.aj),a.aj=null)},b7=function(a){a.g.ow()||a.Og||a.g.Mn(a)},a7=function(a){i7(a);
g.qf(a.Zn);a.Zn=null;a.i.stop();g.An(a.ca);if(a.wc){var b=a.wc;a.wc=null;b.abort();b.dispose()}a.Ge&&(a.Ge=null)},$6=function(a,b){try{a.g.iz(a,b),a.g.ze(4)}catch(c){}},k7=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;j7(a,b,function(k){k?c(!0):g.u.setTimeout(function(){k7(a,b,c,d,f)},f)})}},j7=function(a,b,c){var d=new Image;
d.onload=function(){try{l7(d),c(!0)}catch(e){}};
d.onerror=function(){try{l7(d),c(!1)}catch(e){}};
d.onabort=function(){try{l7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{l7(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
k6(d,a)},l7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},m7=function(a){this.g=a;
this.i=new R6},o7=function(a){var b=n7(a.g,a.nj,"/mail/images/cleardot.gif");
X5(b);k7(b.toString(),5E3,(0,g.x)(a.FC,a),3,2E3);a.ze(1)},q7=function(a){var b=a.g.F;
if(null!=b)Y6(5),b?(Y6(11),p7(a.g,a,!1)):(Y6(12),p7(a.g,a,!0));else if(a.Gd=new S6(a,void 0,void 0,void 0),a.Gd.Zg=a.kq,b=a.g,b=n7(b,b.Wk()?a.Uj:null,a.lq),Y6(5),!g.Ld||g.od(10))Y5(b,"TYPE","xmlhttp"),V6(a.Gd,b,!1,a.Uj,!1);else{Y5(b,"TYPE","html");var c=a.Gd;a=!!a.Uj;c.Yh=3;c.ag=X5(b.clone());f7(c,a)}},r7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new R6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Gqa=function(a,b){this.g=a;
this.map=b;this.context=null},s7=function(a){g.sf.call(this,"statevent",a)},t7=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},u7=function(a){g.sf.call(this,"serverreachability",a)},y7=function(a){v7(a);
if(3==a.g){var b=a.Bk++,c=a.pm.clone();g.sn(c,"SID",a.l);g.sn(c,"RID",b);g.sn(c,"TYPE","terminate");w7(a,c);b=new S6(a,a.l,b,void 0);b.Yh=2;b.ag=X5(c.clone());k6(new Image,b.ag.toString());b.Hi=(0,g.D)();W6(b)}x7(a)},A7=function(a){a.YC(1,0);
a.pm=n7(a,null,a.jq);z7(a)},v7=function(a){a.hg&&(a.hg.abort(),a.hg=null);
a.Ub&&(a.Ub.cancel(),a.Ub=null);a.qf&&(g.u.clearTimeout(a.qf),a.qf=null);B7(a);a.Dd&&(a.Dd.cancel(),a.Dd=null);a.og&&(g.u.clearTimeout(a.og),a.og=null)},C7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Gqa(a.TH++,b));2!=a.g&&3!=a.g||z7(a)},z7=function(a){a.Dd||a.og||(a.og=h7((0,g.x)(a.nz,a),0),a.Rh=0)},Iqa=function(a,b){if(1==a.g){if(!b){a.Bk=Math.floor(1E5*Math.random());
var c=a.Bk++,d=new S6(a,"",c,void 0);d.Zg=null;var e=D7(a),f=a.pm.clone();g.sn(f,"RID",c);g.sn(f,"CVER","1");w7(a,f);U6(d,f,e);a.Dd=d;a.g=2}}else 3==a.g&&(b?Hqa(a,b):0==a.i.length||a.Dd||Hqa(a))},Hqa=function(a,b){if(b)if(6<a.Pg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Bk-1;var d=D7(a)}else c=b.B,d=b.sh;else c=a.Bk++,d=D7(a);var e=a.pm.clone();g.sn(e,"SID",a.l);g.sn(e,"RID",c);g.sn(e,"AID",a.ki);w7(a,e);c=new S6(a,a.l,c,a.Rh+1);c.Zg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Dd=c;U6(c,e,d)},w7=function(a,b){if(a.Wc){var c=a.Wc.Ov();
c&&g.Kb(c,function(d,e){g.sn(b,e,d)})}},D7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Pg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Pg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},Jqa=function(a){a.Ub||a.qf||(a.B=1,a.qf=h7((0,g.x)(a.mz,a),0),a.Kh=0)},E7=function(a){if(a.Ub||a.qf||3<=a.Kh)return!1;
a.B++;a.qf=h7((0,g.x)(a.mz,a),Kqa(a,a.Kh));a.Kh++;return!0},p7=function(a,b,c){a.Eo=c;
a.Me=b.Bf;a.A||A7(a)},B7=function(a){null!=a.Tg&&(g.u.clearTimeout(a.Tg),a.Tg=null)},Kqa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},F7=function(a,b){if(2==b||9==b){var c=null;
a.Wc&&(c=null);var d=(0,g.x)(a.UM,a);c||(c=new g.kn("//www.google.com/images/cleardot.gif"),X5(c));j7(c.toString(),1E4,d)}else Y6(2);Lqa(a,b)},Lqa=function(a,b){a.g=0;
a.Wc&&a.Wc.Ru(b);x7(a);v7(a)},x7=function(a){a.g=0;
a.Me=-1;if(a.Wc)if(0==a.o.length&&0==a.i.length)a.Wc.vp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Wc.vp(b)}},n7=function(a,b,c){var d=g.tn(c);
if(""!=d.g)b&&g.mn(d,b+"."+d.g),g.nn(d,d.u);else{var e=window.location;d=sqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Cj&&g.Kb(a.Cj,function(f,k){g.sn(d,k,f)});
g.sn(d,"VER",a.Pg);w7(a,d);return d},h7=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},Y6=function(a){G7.dispatchEvent(new s7(G7,a))},Mqa=function(){},Nqa=function(a,b){this.action=a;
this.params=b||{}},H7=function(a,b){g.A.call(this);
this.g=new g.J(this.vL,0,this);g.B(this,this.g);this.Zc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},I7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Yo;this.i=new H7(this.yM,this);this.g=null;this.ib=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},Oqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Eo,sessionId:a.g.l,arrayId:a.g.ki}},Pqa=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&Iqa(a.g),y7(a.g));a.D=0},J7=function(a){return!!a.g&&3==a.g.g},Qqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},K7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},L7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.bh(c+b,{})},M7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),ne:g.Qa(a.u,e)};c&&(a.vb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.br(b,a)},Uqa=function(){var a=Rqa;
Sqa();N7.push(a);Tqa(N7)},O7=function(a,b){Sqa();
var c=N7,d=Vqa(a,String(b));0==c.length?Wqa(d):(Tqa(c),(0,g.y)(c,function(e){e(d)}))},Sqa=function(){N7||(N7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",N7,void 0))},Wqa=function(a){var b=(P7+1)%50;
P7=b;Q7[b]=a;R7||(R7=49==b)},Tqa=function(a){var b=Q7;
if(b[0]){var c=P7,d=R7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
Q7=Array(50);P7=-1;R7=!1}},Vqa=function(a,b){var c=((0,g.D)()-Xqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},S7=function(a){g.N.call(this);
this.B=a;this.g=[]},Yqa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Zqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!w6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Yqa(a,b[d])||c;return c},$qa=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},T7=function(a,b,c,d){g.N.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Aa=NaN},V7=function(a){S7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;U7(this);this.info("Initializing with "+u6(this.g))},ara=function(a){if(a.g.length){var b=(0,g.ge)(a.g,function(d){return d.id}),c=L7(a.l,"/pairing/get_lounge_token_batch");
M7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.ID,a),(0,g.x)(a.HD,a))}},U7=function(a){var b=s6(F6());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return Zqa(a,b)},W7=function(a,b){Aqa((0,g.ge)(a.g,r6));
b&&G6()},Y7=function(a,b){g.N.call(this);
this.A=b;var c=g.Ht("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;X7("Initialized with "+g.Kg(this.g))},bra=function(a,b,c){var d=L7(a.u,"/pairing/get_screen_availability");
M7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},Z7=function(a,b){a:if(j6(b)!=j6(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(X7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.M("screenChange"));cra(a)},$7=function(a){isNaN(a.l)||g.gq(a.l);
a.l=g.eq((0,g.x)(a.Cs,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},X7=function(a){O7("OnlineScreenService",a)},dra=function(a){var b={};
(0,g.y)(a.A(),function(c){c.token?b[c.token]=c.id:this.Gb("Requesting availability of screen w/o lounge token.")});
return b},cra=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Gt("yt-remote-online-screen-ids",a.join(","),60):y6("yt-remote-online-screen-ids")},a8=function(a){S7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};era(this)},gra=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Qd();if(k=(c?x6(k,c):null)||x6(k,b)){k.uuid=b;var l=b8(a,k);bra(a.i,l,function(m){e(m?l:null)})}else c?fra(a,c,(0,g.x)(function(m){var n=b8(this,new p6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));bra(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},hra=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},fra=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={vb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.br(L7(a.A,"/pairing/get_lounge_token_batch"),e)},ira=function(a){a.g=a.l.Qd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+u6(a.g))},era=function(a){c8(a);
a.l=new V7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.QD,a));ira(a);a.o=s6(g.Ht("yt-remote-automatic-screen-cache")||[]);c8(a);a.info("Initializing automatic screens: "+u6(a.o));a.i=new Y7(a.A,(0,g.x)(a.Qd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.M("onlineScreenChange")},a))},b8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=x6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Gt("yt-remote-automatic-screen-cache",(0,g.ge)(a.o,r6)));c8(a);a.u[b.uuid]=b.id;g.Gt("yt-remote-device-id-map",a.u,31536E3);return b},c8=function(a){a.u=g.Ht("yt-remote-device-id-map")||{}},d8=function(a,b,c){g.N.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},e8=function(a,b){O7(a.P,b)},f8=function(a,b){d8.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.zN,this);this.u=(0,g.x)(this.YL,this);this.o=g.eq((0,g.x)(function(){jra(this,null)},this),12E4)},kra=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.x)(function(){e8(this,"Failed to send message: getMdxSessionStatus.")},a)):e8(a,"Sending yt message without session: "+g.Kg(b))},jra=function(a,b){g.gq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.On,a),d=(0,g.x)(a.Td,a);a.gw(b,c,d,5)}}else a.Td(Error("Waiting for session status timed out."))},g8=function(a,b,c){d8.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.N=c;this.u=null;this.B=g.Ha;this.A=NaN;this.I=(0,g.x)(this.CN,this);this.g=g.Ha},lra=function(a){a.g=a.F.tB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ha;
this.On(b)},a),(0,g.x)(function(b){this.g=g.Ha;
this.Td(b)},a))},mra=function(a){var b={};
b.pairingCode=a.H;b.theme=a.N;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}J6()&&(b.env_useStageMdx=1);return g.$g(b)},h8=function(a,b){d8.call(this,a,b,"ManualSession");
this.g=g.eq((0,g.x)(this.mi,this,null),150)},i8=function(a,b,c,d){g.N.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.DK,this)},nra=function(a,b){return b?g.Xa(a.l,function(c){return q6(b,c.label)},a):null},j8=function(a){O7("Controller",a)},Rqa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},k8=function(a){return a.u||!!a.l.length||!!a.g},l8=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.M("yt-remote-cast2-receiver-resumed",b.i):a.M("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.lz,a,b)),b.l?a.M("yt-remote-cast2-session-change",b.l):c&&a.g.mi(null)):a.M("yt-remote-cast2-session-change",null))},ora=function(a){var b=a.i.sB(),c=a.g&&a.g.i;
a=(0,g.ge)(b,function(d){c&&q6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=nra(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},ura=function(a,b,c,d,e,f,k){pra()?qra(b,e,f,k)&&(n8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?rra(a,c):(window.__onGCastApiAvailable=function(l,m){l?rra(a,c):(o8("Failed to load cast API: "+m),p8(!1),n8(!1),y6("yt-remote-cast-available"),y6("yt-remote-cast-receiver"),sra(),c(!1))},d?g.rq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Eqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?O6():(P6(),N6(tra.map(Cqa))))):m8("Cannot initialize because not running Chrome")},sra=function(){m8("dispose");
var a=q8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);vra(!1);g.mq(r8);r8.length=0},s8=function(){return!!g.Ht("yt-remote-cast-installed")},wra=function(){var a=g.Ht("yt-remote-cast-receiver");
return a?a.friendlyName:null},xra=function(){m8("clearCurrentReceiver");
y6("yt-remote-cast-receiver")},yra=function(){return s8()?q8()?q8().getCastSession():(o8("getCastSelector: Cast is not initialized."),null):(o8("getCastSelector: Cast API is not installed!"),null)},u8=function(){s8()?q8()?t8()?(m8("Requesting cast selector."),q8().requestSession()):(m8("Wait for cast API to be ready to request the session."),r8.push(g.lq("yt-remote-cast2-api-ready",u8))):o8("requestCastSelector: Cast is not initialized."):o8("requestCastSelector: Cast API is not installed!")},v8=
function(a,b){t8()?q8().setConnectedScreenStatus(a,b):o8("setConnectedScreenStatus called before ready.")},pra=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.px||a},zra=function(a,b){q8().init(a,b)},qra=function(a,b,c,d){var e=!1;
q8()||(a=new i8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Gt("yt-remote-cast-available",f);n6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){m8("onReceiverSelected: "+f.friendlyName);
g.Gt("yt-remote-cast-receiver",f);n6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){m8("onReceiverResumed: "+f.friendlyName);
g.Gt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){m8("onSessionChange: "+t6(f));
f||y6("yt-remote-cast-receiver");n6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
m8("cloudview.createSingleton_: "+e);return e},q8=function(){return g.w("yt.mdx.remote.cloudview.instance_")},rra=function(a,b){p8(!0);
n8(!1);zra(a,function(c){c?(vra(!0),g.oq("yt-remote-cast2-api-ready")):(o8("Failed to initialize cast API."),p8(!1),y6("yt-remote-cast-available"),y6("yt-remote-cast-receiver"),sra());b(c)})},m8=function(a){O7("cloudview",a)},o8=function(a){O7("cloudview",a)},p8=function(a){m8("setCastInstalled_ "+a);
g.Gt("yt-remote-cast-installed",a)},t8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},vra=function(a){m8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},n8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},w8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Ne=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},x8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ne=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},y8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},z8=function(a,b){a.B=b;
a.A=(0,g.D)()},A8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},B8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&x8(a)},C8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Ne;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},E8=function(a,b){g.N.call(this);
this.g=0;this.o=a;this.A=[];this.u=new m6;this.l=this.i=null;this.F=(0,g.x)(this.BI,this);this.B=(0,g.x)(this.Ek,this);this.D=(0,g.x)(this.AI,this);this.H=(0,g.x)(this.QI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Bt,this),Ara(this))):c=3;0!=c&&(b?this.Bt(c):g.eq((0,g.x)(function(){this.Bt(c)},this),0));
var d=yra();d&&D8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},F8=function(a){return new w8(a.o.getPlayerContextData())},Ara=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.AK,b),this))},a)},Bra=function(a){(0,g.y)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},G8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},I8=function(a,b,c){var d=F8(a);
z8(d,c);-1E3!=d.playerState&&(d.playerState=b);H8(a,d)},J8=function(a,b,c){a.o.sendMessage(b,c)},H8=function(a,b){Bra(a);
a.o.setPlayerContextData(C8(b));Ara(a)},D8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.Ek(null));
a.l=b;a.l&&(O7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.Ek(a.l.media[0]))},Cra=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=F8(a);b.contentId!=d.videoId&&O7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;z8(d,a.i.getEstimatedTime());H8(a,d)}else O7("CP","No cast media video. Ignoring state update.")},K8=function(a,b,c){return(0,g.x)(function(d){this.Gb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gb("Retrying "+b+" using MDx browser channel."),J8(this,b,c))},a)},L8=function(a,b,c){g.N.call(this);
this.u=NaN;this.I=!1;this.D=this.B=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Pa=this.g=null;this.R=a;this.P.push(g.js(window,"beforeunload",(0,g.x)(this.BD,this)));this.i=[];this.Pa=new w8;this.N=b.id;this.g=Dra(this,c);this.g.subscribe("handlerOpened",this.GI,this);this.g.subscribe("handlerClosed",this.CI,this);this.g.subscribe("handlerError",this.DI,this);this.g.subscribe("handlerMessage",this.FI,this);Qqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Pa.videoId;
g.It()&&g.Gt("yt-remote-session-video-id",d)},this)},M8=function(a){O7("conn",a)},Dra=function(a,b){return new I7(L7(a.R,"/bc"),b)},N8=function(a,b){a.M("proxyStateChange",b)},Era=function(a){a.u=g.eq((0,g.x)(function(){M8("Connecting timeout");
this.Oh(1)},a),2E4)},O8=function(a){g.gq(a.u);
a.u=NaN},P8=function(a){g.gq(a.H);
a.H=NaN},Fra=function(a){Q8(a);
a.F=g.eq((0,g.x)(function(){R8(this,"getNowPlaying")},a),2E4)},Q8=function(a){g.gq(a.F);
a.F=NaN},Hra=function(a,b){b&&(O8(a),P8(a));
b==(J7(a.g)&&isNaN(a.u))?b&&(N8(a,1),R8(a,"getSubtitlesTrack")):b?(a.dw()&&a.Pa.reset(),N8(a,1),R8(a,"getNowPlaying"),Gra(a)):a.Oh(1)},Ira=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.Xb(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.M("remotePlayerChange"))},Jra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;B8(a.Pa,c,d);a.M("remoteQueueChange")},Lra=function(a,b){b.params=b.params||{};
Jra(a,b);Kra(a,b);a.M("autoplayDismissed")},Kra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
z8(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?Fra(a):Q8(a);a.M("remotePlayerChange")},Mra=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);z8(a.Pa,isNaN(c)?0:c);a.M("remotePlayerChange")}},Nra=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.M("remotePlayerChange")},Ora=function(a,b){a.A=b.params.videoId;
a.M("nowAutoplaying",parseInt(b.params.timeout,10))},Pra=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Ne="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.M("previousNextChange")},Gra=function(a){g.gq(a.D);
a.D=g.eq((0,g.x)(a.Oh,a,1),864E5)},R8=function(a,b,c){c?M8("Sending: action="+b+", params="+g.Kg(c)):M8("Sending: action="+b);
a.g.sendMessage(b,c)},S8=function(a){S7.call(this,"ScreenServiceProxy");
this.Yc=a;this.i=[];this.i.push(this.Yc.$_s("screenChange",(0,g.x)(this.xN,this)));this.i.push(this.Yc.$_s("onlineScreenChange",(0,g.x)(this.fK,this)))},Ura=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Xp("MDX_CONFIG")||b;yqa();D6();T8||(T8=new K7(b?b.loungeApiHost:void 0),J6()&&(T8.g="/api/loungedev"));U8||(U8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",U8,void 0));Qra();var c=V8();if(!c){var d=new a8(T8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=V8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);ura(a,d,function(m){m?W8()&&v8(W8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){n6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),X8("Initializing: "+g.Kg(b)),Y8.push(g.lq("yt-remote-cast2-availability-change",function(){n6("yt-remote-receiver-availability-change")})),Y8.push(g.lq("yt-remote-cast2-receiver-selected",function(){Z8(null);
n6("yt-remote-auto-connect","cast-selector-receiver")})),Y8.push(g.lq("yt-remote-cast2-receiver-resumed",function(){n6("yt-remote-receiver-resumed","cast-selector-receiver")})),Y8.push(g.lq("yt-remote-cast2-session-change",Rra)),Y8.push(g.lq("yt-remote-connection-change",function(m){m?v8(W8(),"YouTube TV"):$8()||(v8(null,null),xra())})),a=a9(),b.isAuto&&(a.id+="#dial"),g.Tq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),X8(" -- with channel params: "+
g.Kg(a)),Sra(a),c.start(),W8()||Tra())},Wra=function(){var a=Vra();
s8()&&g.Ht("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Vra=function(){var a=V8().Yc.$_gos();
var b=b9();b&&c9()&&(w6(a,b)||a.push(b));return xqa(a)},d9=function(){var a=Xra();
!a&&s8()&&wra()&&(a={key:"cast-selector-receiver",name:wra()});return a},Xra=function(){var a=Vra(),b=b9();
b||(b=$8());return g.Xa(a,function(c){return b&&q6(b,c.key)?!0:!1})},b9=function(){var a=W8();
if(!a)return null;var b=V8().Qd();return x6(b,a)},Rra=function(a){X8("remote.onCastSessionChange_: "+t6(a));
if(a){var b=b9();b&&b.id==a.id?v8(b.id,"YouTube TV"):(b&&e9(),f9(a,1))}else c9()&&e9()},e9=function(){t8()?q8().stopSession():o8("stopSession called before API ready.");
var a=c9();a&&(a.disconnect(1),g9(null))},h9=function(){var a=c9();
return!!a&&3!=a.getProxyState()},X8=function(a){O7("remote",a)},V8=function(){if(!i9){var a=g.w("yt.mdx.remote.screenService_");
i9=a?new S8(a):null}return i9},W8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Yra=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},Zra=function(){return g.w("yt.mdx.remote.connectData_")},Z8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},c9=function(){return g.w("yt.mdx.remote.connection_")},g9=function(a){var b=c9();
Z8(null);a||Yra("");g.Ga("yt.mdx.remote.connection_",a,void 0);U8&&((0,g.y)(U8,function(c){c(a)}),U8.length=0);
b&&!a?n6("yt-remote-connection-change",!1):!b&&a&&n6("yt-remote-connection-change",!0)},$8=function(){var a=g.It();
if(!a)return null;var b=V8().Qd();return x6(b,a)},f9=function(a,b){b9()&&b9();
if(j9)k9=a;else{Yra(a.id);var c=new L8(T8,a,a9());c.connect(b,Zra());c.subscribe("beforeDisconnect",function(d){n6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){c9()&&g9(null)});
g9(c)}},Tra=function(){var a=$8();
a?(X8("Resume connection to: "+t6(a)),f9(a,0)):(H6(),xra(),X8("Skipping connecting because no session screen found."))},Qra=function(){var a=a9();
if(g.Xb(a)){a=C6();var b=g.Ht("yt-remote-session-name")||"",c=g.Ht("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},a9=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Sra=function(a){a?(g.Gt("yt-remote-session-app",a.app),g.Gt("yt-remote-session-name",a.name)):(y6("yt-remote-session-app"),y6("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},l9=function(a,b,c){g.A.call(this);
this.u=a;this.i=b;this.l=new g.Ts(this);g.B(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.AJ);this.l.K(b,"captionschanged",this.zI);this.l.K(b,"captionssettingschanged",this.GA);this.l.K(b,"videoplayerreset",this.Pn);this.l.K(b,"mdxautoplaycancel",this.EC);this.R=this.l.K(b,"onVolumeChange",this.Vy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.hz,this);c.subscribe("remotePlayerChange",this.Gk,this);c.subscribe("remoteQueueChange",this.Pn,this);c.subscribe("autoplayUpNext",this.Ky,
this);c.subscribe("previousNextChange",this.ez,this);c.subscribe("nowAutoplaying",this.az,this);c.subscribe("autoplayDismissed",this.Jy,this);this.suggestion=null;this.F=new g.OC(64);this.o=new g.J(this.EA,500,this);g.B(this,this.o);this.A=new g.J(this.FA,1E3,this);g.B(this,this.A);this.I=new Q6(this.dN,0,this);g.B(this,this.I);this.B={};this.P=new g.J(this.gB,1E3,this);g.B(this,this.P);this.H=new g.Jl(this.XF,1E3,this);g.B(this,this.H);this.N=g.Ha;this.GA();this.Pn();this.Gk()},m9=function(a,b){a.u.Nc(b,
a.i.getVideoData().lengthSeconds)},$ra=function(a){m9(a,0);
a.o.stop();n9(a,new g.OC(64))},p9=function(a,b){if(o9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.vA(a.i.getVideoData(1).videoId,c);a.B=F8(a.g).g}},q9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Gf,i6(c));n9(a,new g.OC(1))},asa=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{bR:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},o9=function(a){return F8(a.g).videoId==a.i.getVideoData(1).videoId},n9=function(a,b){a.A.stop();
var c=a.F;if(!g.UC(c,b)){var d=g.T(b,2);d!=g.T(a.F,2)&&g.KK(a.i,d);a.F=b;bsa(a.u,c,b)}},r9=function(){g.W.call(this,{C:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{C:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{C:"div",G:"ytp-mdx-popup-title",V:"You're signed out"},{C:"div",G:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{C:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.l=new g.CQ(this,250);g.B(this,this.l);this.B=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.B,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},s9=function(a){g.W.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.RP()]},{C:"div",G:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.l=new g.CQ(this,250);g.B(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);csa(this,g.GK(a))},csa=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.QN("Error on $RECEIVER_NAME",c):g.VC(b)||g.T(b,4)?g.QN("Playing on $RECEIVER_NAME",c):g.QN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},t9=function(a,b){g.nU.call(this,"Play on",0,a,b);
this.l=a;this.B={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},u9=function(a){g.iL.call(this,a);
this.i={key:v6(),name:"This computer"};this.u=null;this.o=[];this.F=this.g=null;this.B=[this.i];this.l=this.i;this.pk=new g.OC(64);this.I=0;this.Um=-1;if(!g.tz(g.X(this.player))){a=this.player;var b=g.HD(a);b&&(b=b.xn())&&(b=new t9(a,b),g.B(this,b));b=new s9(a);g.B(this,b);g.VK(a,b.element,4);this.H=new r9;g.B(this,this.H);g.VK(a,this.H.element,4);this.D=!!$8()}this.A=null},v9=function(a){a.A&&(a.player.removeEventListener("presentingplayerstatechange",a.A),a.A=null)},bsa=function(a,b,c){a.pk=c;
a.player.M("presentingplayerstatechange",new g.YD(c,b))},w9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)e9();
else{var c;if(c=g.O(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))c=g.Xp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Xp("SESSION_INDEX")||g.Xp("LOGGED_IN"));c&&!a.D&&(g.VC(g.GK(a.player))||(a.A=(0,g.x)(a.fM,a),a.player.addEventListener("presentingplayerstatechange",a.A)),a.player.pauseVideo(),a.H.l.show(),c9()||(j9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<
f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Gf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=i6(c))&&(d.locationInfo=c);c=d}else c=null;X8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(Z8(c||null),t8()?q8().setLaunchParams(c||null):o8("setLaunchParams called before ready.")):!c&&h9()&&W8()==b.key?n6("yt-remote-connection-change",!0):(e9(),
Z8(c||null),c=V8().Qd(),(c=x6(c,b.key))&&f9(c,1))}},nqa=/^https?$/i,dsa=["POST",
"PUT"];g.Sa(g6,g.Qf);g.h=g6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.Y=b;this.R=!1;this.i=!0;this.g=this.N?Z5(this.N):Z5(g.rZ);this.P=this.N?this.N.getOptions():g.rZ.getOptions();this.g.onreadystatechange=(0,g.x)(this.qw,this);try{W5($5(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){W5($5(this,"Error opening Xhr: "+f.message));d6(this,f);return}a=
c||"";var e=this.headers.clone();d&&kqa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Od(),lqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.$a(dsa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{a6(this),0<this.A&&(this.I=mqa(this.g),W5($5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.rw,this)):this.F=g.Gg(this.rw,this.A,this)),W5($5(this,"Sending request")),this.B=!0,this.g.send(a),this.B=!1}catch(f){W5($5(this,"Send error: "+f.message)),d6(this,f)}};
g.h.rw=function(){"undefined"!=typeof g.UY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,$5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&($5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),c6(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),c6(this,!0));g6.bb.U.call(this)};
g.h.qw=function(){this.fa()||(this.aa||this.B||this.o?f6(this):this.CK())};
g.h.CK=function(){f6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<e6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.l)?this.l:String(this.l)};
var e7={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},d7={"'":"\\'"},esa={};g.h=m6.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Vma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.Bc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var vqa={WN:"atp",mQ:"ska",bQ:"que",BP:"mus",lQ:"sus",SO:"dsp",iQ:"seq"};o6.prototype.jg=function(){var a=new o6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var I6,B6="",Dqa=K6("loadCastFramework")||K6("loadCastApplicationFramework"),tra=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(Q6,g.A);g.h=Q6.prototype;g.h.xD=function(a){this.o=arguments;this.g=!1;this.Aa?this.l=(0,g.D)()+this.Zc:this.Aa=g.Gg(this.u,this.Zc)};
g.h.stop=function(){this.Aa&&(g.u.clearTimeout(this.Aa),this.Aa=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();Q6.bb.U.call(this)};
g.h.yD=function(){this.l?(this.Aa=g.Gg(this.u,this.l-(0,g.D)()),this.l=null):(this.Aa=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};R6.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
R6.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};g.h=S6.prototype;g.h.Zg=null;g.h.Ce=!1;g.h.aj=null;g.h.xt=null;g.h.Hi=null;g.h.Yh=null;g.h.ag=null;g.h.Eg=null;g.h.sh=null;g.h.wc=null;g.h.nl=0;g.h.Ge=null;g.h.Go=null;g.h.rg=null;g.h.Vj=-1;g.h.iA=!0;g.h.Og=!1;g.h.mq=0;g.h.Zn=null;var Z6={},X6={};g.h=S6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.oM=function(a){a=a.target;var b=this.Zn;b&&3==e6(a)?b.Rj():this.oB(a)};
g.h.oB=function(a){try{if(a==this.wc)a:{var b=e6(this.wc),c=this.wc.u,d=this.wc.getStatus();if(g.Ld&&!g.od(10)||g.Nd&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!h6(this.wc))break a;this.Og||4!=b||7==c||(8==c||0>=d?this.g.ze(3):this.g.ze(2));i7(this);var e=this.wc.getStatus();this.Vj=e;var f=h6(this.wc);(this.Ce=200==e)?(4==b&&a7(this),this.u?(c7(this,b,f),g.Ch&&this.Ce&&3==b&&(this.ca.da(this.i,"tick",this.iM),this.i.start())):$6(this,f),this.Ce&&!this.Og&&(4==b?this.g.Mn(this):(this.Ce=
!1,W6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.rg=3,Y6(13)):(this.rg=0,Y6(14)),a7(this),b7(this))}}catch(k){this.wc&&h6(this.wc)}finally{}};
g.h.iM=function(){var a=e6(this.wc),b=h6(this.wc);this.nl<b.length&&(i7(this),c7(this,a,b),this.Ce&&4!=a&&W6(this))};
g.h.DL=function(a){h7((0,g.x)(this.CL,this,a),0)};
g.h.CL=function(a){this.Og||(i7(this),$6(this,a),W6(this))};
g.h.oz=function(a){h7((0,g.x)(this.BL,this,a),0)};
g.h.BL=function(a){this.Og||(a7(this),this.Ce=a,this.g.Mn(this),this.g.ze(4))};
g.h.cancel=function(){this.Og=!0;a7(this)};
g.h.NL=function(){this.aj=null;var a=(0,g.D)();0<=a-this.xt?(2!=this.Yh&&this.g.ze(3),a7(this),this.rg=2,Y6(18),b7(this)):g7(this,this.xt-a)};
g.h.getLastError=function(){return this.rg};g.h=m7.prototype;g.h.kq=null;g.h.Gd=null;g.h.ao=!1;g.h.pw=null;g.h.nm=null;g.h.Uq=null;g.h.lq=null;g.h.ge=null;g.h.Bf=-1;g.h.Uj=null;g.h.nj=null;g.h.connect=function(a){this.lq=a;a=n7(this.g,null,this.lq);Y6(3);this.pw=(0,g.D)();var b=this.g.D;null!=b?(this.Uj=b[0],(this.nj=b[1])?(this.ge=1,o7(this)):(this.ge=2,q7(this))):(Y5(a,"MODE","init"),this.Gd=new S6(this,void 0,void 0,void 0),this.Gd.Zg=this.kq,V6(this.Gd,a,!1,null,!0),this.ge=0)};
g.h.FC=function(a){if(a)this.ge=2,q7(this);else{Y6(4);var b=this.g;b.Me=b.hg.Bf;F7(b,9)}a&&this.ze(2)};
g.h.Hp=function(a){return this.g.Hp(a)};
g.h.abort=function(){this.Gd&&(this.Gd.cancel(),this.Gd=null);this.Bf=-1};
g.h.ow=function(){return!1};
g.h.iz=function(a,b){this.Bf=a.Vj;if(0==this.ge)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Me=this.Bf;F7(c,2);return}this.Uj=c[0];this.nj=c[1]}else c=this.g,c.Me=this.Bf,F7(c,2);else if(2==this.ge)if(this.ao)Y6(7),this.Uq=(0,g.D)();else if("11111"==b){if(Y6(6),this.ao=!0,this.nm=(0,g.D)(),c=this.nm-this.pw,!g.Ld||g.od(10)||500>c)this.Bf=200,this.Gd.cancel(),Y6(12),p7(this.g,this,!0)}else Y6(8),this.nm=this.Uq=(0,g.D)(),this.ao=!1};
g.h.Mn=function(){this.Bf=this.Gd.Vj;if(this.Gd.Ce)0==this.ge?this.nj?(this.ge=1,o7(this)):(this.ge=2,q7(this)):2==this.ge&&((!g.Ld||g.od(10)?!this.ao:200>this.Uq-this.nm)?(Y6(11),p7(this.g,this,!1)):(Y6(12),p7(this.g,this,!0)));else{0==this.ge?Y6(9):2==this.ge&&Y6(10);var a=this.g;this.Gd.getLastError();a.Me=this.Bf;F7(a,2)}};
g.h.Wk=function(){return this.g.Wk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ze=function(a){this.g.ze(a)};g.h=r7.prototype;g.h.Cj=null;g.h.Dd=null;g.h.Ub=null;g.h.jq=null;g.h.pm=null;g.h.Fu=null;g.h.Dm=null;g.h.Bk=0;g.h.TH=0;g.h.Wc=null;g.h.og=null;g.h.qf=null;g.h.Tg=null;g.h.hg=null;g.h.Eo=null;g.h.ki=-1;g.h.Yw=-1;g.h.Me=-1;g.h.Rh=0;g.h.Kh=0;g.h.Pg=8;var G7=new g.Qf;g.Sa(s7,g.sf);g.Sa(t7,g.sf);g.Sa(u7,g.sf);g.h=r7.prototype;g.h.connect=function(a,b,c,d,e){Y6(0);this.jq=b;this.Cj=c||{};d&&g.Ca(e)&&(this.Cj.OSID=d,this.Cj.OAID=e);this.A?(h7((0,g.x)(this.Zu,this,a),100),A7(this)):this.Zu(a)};
g.h.Zu=function(a){this.hg=new m7(this);this.hg.kq=null;this.hg.i=this.u;this.hg.connect(a)};
g.h.ow=function(){return 0==this.g};
g.h.nz=function(a){this.og=null;Iqa(this,a)};
g.h.mz=function(){this.qf=null;this.Ub=new S6(this,this.l,"rpc",this.B);this.Ub.Zg=null;this.Ub.mq=0;var a=this.Fu.clone();g.sn(a,"RID","rpc");g.sn(a,"SID",this.l);g.sn(a,"CI",this.Eo?"0":"1");g.sn(a,"AID",this.ki);w7(this,a);if(!g.Ld||g.od(10))g.sn(a,"TYPE","xmlhttp"),V6(this.Ub,a,!0,this.Dm,!1);else{g.sn(a,"TYPE","html");var b=this.Ub,c=!!this.Dm;b.Yh=3;b.ag=X5(a.clone());f7(b,c)}};
g.h.iz=function(a,b){if(0!=this.g&&(this.Ub==a||this.Dd==a))if(this.Me=a.Vj,this.Dd==a&&3==this.g)if(7<this.Pg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.qf){if(this.Ub)if(this.Ub.Hi+3E3<this.Dd.Hi)B7(this),this.Ub.cancel(),this.Ub=null;else break a;E7(this);Y6(19)}}else this.Yw=c[1],0<this.Yw-this.ki&&37500>c[2]&&this.Eo&&0==this.Kh&&!this.Tg&&(this.Tg=h7((0,g.x)(this.vI,this),6E3));else F7(this,11)}else b!=esa.tO.g&&F7(this,11);else if(this.Ub==a&&
B7(this),!g.wb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.ki=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Dm=e[2],e=e[3],null!=e?this.Pg=e:this.Pg=6,this.g=3,this.Wc&&this.Wc.Tu(),this.Fu=n7(this,this.Wk()?this.Dm:null,this.jq),Jqa(this)):"stop"==e[0]&&F7(this,7):3==this.g&&("stop"==e[0]?F7(this,7):"noop"!=e[0]&&this.Wc&&this.Wc.Su(e),this.Kh=0)}}};
g.h.vI=function(){null!=this.Tg&&(this.Tg=null,this.Ub.cancel(),this.Ub=null,E7(this),Y6(20))};
g.h.Mn=function(a){if(this.Ub==a){B7(this);this.Ub=null;var b=2}else if(this.Dd==a)this.Dd=null,b=1;else return;this.Me=a.Vj;if(0!=this.g)if(a.Ce)1==b?(b=(0,g.D)()-a.Hi,G7.dispatchEvent(new t7(G7,a.sh?a.sh.length:0,b,this.Rh)),z7(this),this.o.length=0):Jqa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Me)){if(d=1==b)this.Dd||this.og||1==this.g||2<=this.Rh?d=!1:(this.og=h7((0,g.x)(this.nz,this,a),Kqa(this,this.Rh)),this.Rh++,d=!0);d=!(d||2==b&&E7(this))}if(d)switch(c){case 1:F7(this,
5);break;case 4:F7(this,10);break;case 3:F7(this,6);break;case 7:F7(this,12);break;default:F7(this,2)}}};
g.h.YC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.UM=function(a){a?Y6(2):(Y6(1),Lqa(this,8))};
g.h.Hp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g6;a.T=!1;return a};
g.h.isActive=function(){return!!this.Wc&&this.Wc.isActive(this)};
g.h.ze=function(a){G7.dispatchEvent(new u7(G7,a))};
g.h.Wk=function(){return!(!g.Ld||g.od(10))};
g.h=Mqa.prototype;g.h.Tu=function(){};
g.h.Su=function(){};
g.h.Ru=function(){};
g.h.vp=function(){};
g.h.Ov=function(){return{}};
g.h.isActive=function(){return!0};g.Sa(H7,g.A);g.h=H7.prototype;g.h.vL=function(){this.Zc=Math.min(3E5,2*this.Zc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Zc+15E3*Math.random();g.Do(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Zc=5E3};g.Sa(I7,Mqa);g.h=I7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Mf=function(a){return this.l.ah(a)};
g.h.M=function(a,b){return this.l.M.apply(this.l,arguments)};
g.h.dispose=function(){this.ib||(this.ib=!0,g.qf(this.l),Pqa(this),g.qf(this.i),this.i=null)};
g.h.fa=function(){return this.ib};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new r7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Wc=null);d.Wc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ki):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):J7(this)&&C7(this.g,c)};
g.h.Tu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)C7(this.g,a[b])}this.M("handlerOpened")};
g.h.Ru=function(a){var b=2==a&&401==this.g.Me;4==a||b||this.i.start();this.M("handlerError",a)};
g.h.vp=function(a){if(!this.i.isActive())this.M("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.Ov=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.Su=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),y7(this.g)):this.M("handlerMessage",new Nqa(a[0],a[1]))};
g.h.yM=function(){this.i.isActive();var a=this.g,b=0;a.Ub&&b++;a.Dd&&b++;0==b&&this.connect(this.u,this.o)};K7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
K7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
K7.prototype.u=function(a){a(Error("request timed out"))};var Xqa=(0,g.D)(),N7=null,Q7=Array(50),P7=-1,R7=!1;g.Sa(S7,g.N);S7.prototype.Qd=function(){return this.g};
S7.prototype.contains=function(a){return!!w6(this.g,a)};
S7.prototype.get=function(a){return a?x6(this.g,a):null};
S7.prototype.info=function(a){O7(this.B,a)};g.t(T7,g.N);g.h=T7.prototype;g.h.start=function(){!this.g&&isNaN(this.Aa)&&this.rB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Aa)||(g.gq(this.Aa),this.Aa=NaN)};
g.h.U=function(){this.stop();g.N.prototype.U.call(this)};
g.h.rB=function(){this.Aa=NaN;this.g=g.br(L7(this.A,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.vN,this),onError:(0,g.x)(this.uN,this),ne:(0,g.x)(this.wN,this)})};
g.h.vN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.M("pairingComplete",new p6(c))};
g.h.uN=function(a){this.g=null;a.status&&404==a.status?this.i>=fsa.length?this.M("pairingFailed",Error("DIAL polling timed out")):(a=fsa[this.i],this.Aa=g.eq((0,g.x)(this.rB,this),a),this.i++):this.M("pairingFailed",Error("Server error "+a.status))};
g.h.wN=function(){this.g=null;this.M("pairingFailed",Error("Server not responding"))};
var fsa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(V7,S7);g.h=V7.prototype;g.h.start=function(){U7(this)&&this.M("screenChange");!g.Ht("yt-remote-lounge-token-expiration")&&ara(this);g.gq(this.i);this.i=g.eq((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){U7(this);Yqa(this,a);W7(this,!1);this.M("screenChange");b(a);a.token||ara(this)};
g.h.remove=function(a,b){var c=U7(this);$qa(this,a)&&(W7(this,!1),c=!0);b(a);c&&this.M("screenChange")};
g.h.Ao=function(a,b,c,d){var e=U7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,W7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.M("screenChange")};
g.h.U=function(){g.gq(this.i);V7.bb.U.call(this)};
g.h.ID=function(a){U7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}W7(this,!b);b&&O7(this.B,"Missed "+b+" lounge tokens.")};
g.h.HD=function(a){O7(this.B,"Requesting lounge tokens failed: "+a)};g.t(Y7,g.N);g.h=Y7.prototype;g.h.start=function(){var a=parseInt(g.Ht("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?$7(this):(this.o=(0,g.D)()+3E5,g.Gt("yt-remote-fast-check-period",this.o),this.Cs())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){X7("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!x6(a,d)},this);
Z7(this,b)};
g.h.U=function(){g.gq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.N.prototype.U.call(this)};
g.h.Cs=function(){g.gq(this.l);this.l=NaN;this.i&&this.i.abort();var a=dra(this);if(j6(a)){var b=L7(this.u,"/pairing/get_screen_availability");this.i=M7(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.x)(this.YK,this,a),(0,g.x)(this.XK,this))}else Z7(this,{}),$7(this)};
g.h.YK=function(a,b){this.i=null;var c=g.Rb(dra(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Z7(this,d);$7(this)}else this.Gb("Changing Screen set during request."),this.Cs()};
g.h.XK=function(a){this.Gb("Screen availability failed: "+a);this.i=null;$7(this)};
g.h.Gb=function(a){O7("OnlineScreenService",a)};g.Sa(a8,S7);g.h=a8.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.M("screenChange"),this.i.isEmpty()||this.M("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Ao=function(a,b,c,d){this.l.contains(a)?this.l.Ao(a,b,c,d):(a="Updating name of unknown screen: "+a.name,O7(this.B,a),d(Error(a)))};
g.h.Qd=function(a){return a?this.g:g.fb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.sB=function(){return(0,g.Xd)(this.Qd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.tB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new T7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d(b8(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.yN=function(a,b,c,d){g.br(L7(this.A,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new p6(f.screen||{});if(!k.name||hra(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);hra(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(b8(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
ne:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.qf(this.l);g.qf(this.i);a8.bb.U.call(this)};
g.h.QD=function(){ira(this);this.M("screenChange");this.i.update()};
a8.prototype.dispose=a8.prototype.dispose;g.Sa(d8,g.N);g.h=d8.prototype;g.h.On=function(a){this.l=a;this.M("sessionScreen",this.l)};
g.h.Td=function(a){this.fa()||(a&&e8(this,""+a),this.l=null,this.M("sessionScreen",null))};
g.h.info=function(a){O7(this.P,a)};
g.h.vB=function(){return null};
g.h.Ls=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){e8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Ls("");d8.bb.U.call(this)};g.Sa(f8,d8);g.h=f8.prototype;g.h.Ks=function(a){if(this.g){if(this.g==a)return;e8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);kra(this)};
g.h.mi=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Td()},this),(0,g.x)(function(){this.Td(Error("Failed to stop receiver app."))},this)):this.Td(Error("Stopping cast device witout session."))};
g.h.Ls=g.Ha;g.h.U=function(){this.info("disposeInternal");g.gq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;f8.bb.U.call(this)};
g.h.YL=function(a,b){if(!this.fa())if(b){var c=l6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":jra(this,c.screenId);break;default:e8(this,"Unknown youtube message: "+d)}}else e8(this,"Unable to parse message.")}else e8(this,"No data in message.")};
g.h.gw=function(a,b,c,d){gra(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(e8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.eq((0,g.x)(this.gw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.vB=function(){return this.g};
g.h.zN=function(a){this.fa()||a||(e8(this,"Cast session died."),this.Td())};g.Sa(g8,d8);g.h=g8.prototype;g.h.Ks=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.mi=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ha;g.gq(this.A);this.o?this.o.stop((0,g.x)(this.Td,this,null),(0,g.x)(this.Td,this,"Failed to stop DIAL device.")):this.Td()};
g.h.U=function(){this.g();this.g=g.Ha;g.gq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;g8.bb.U.call(this)};
g.h.CN=function(a){this.fa()||a||(e8(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Td())};
g.h.Bq=function(a){this.H=v6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,mra(this));a(b);lra(this)}else this.B=(0,g.x)(function(){g.gq(this.A);this.B=g.Ha;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,mra(this));a(c);lra(this)},this),this.A=g.eq((0,g.x)(function(){this.B()},this),100)};
g.h.lE=function(a,b,c){gra(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.On(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Bq(b,c)},this),(0,g.x)(function(d){e8(this,"Failed to get DIAL screen: "+d);
this.Bq(b,c)},this))};g.Sa(h8,d8);h8.prototype.stop=function(){this.Td()};
h8.prototype.Ks=g.Ha;h8.prototype.mi=function(){g.gq(this.g);this.g=NaN;var a=x6(this.F.Qd(),this.i.label);a?this.On(a):this.Td(Error("No such screen"))};
h8.prototype.U=function(){g.gq(this.g);this.g=NaN;h8.bb.U.call(this)};g.Sa(i8,g.N);g.h=i8.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.HK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.kz,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.XI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),Uqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.uB,this)),this.l=ora(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(k){this.Gb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.M("yt-remote-cast2-availability-change",k8(this)),b(!0))},this),(0,g.x)(function(k){this.Gb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.HM=function(a,b){j8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)j8("Unsetting old screen status: "+this.g.i.friendlyName),l8(this,null)}if(a&&b){if(!this.g){c=x6(this.i.Qd(),a);if(!c){j8("setConnectedScreenStatus: Unknown screen.");return}var d=nra(this,c);d||(j8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.x)(function(e){this.Gb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
j8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);l8(this,new h8(this.i,d),!0)}this.g.Ls(b)}else j8("setConnectedScreenStatus: no screen.")};
g.h.IM=function(a){this.fa()?this.Gb("Setting connection data on disposed cast v2"):this.g?this.g.mi(a):this.Gb("Setting connection data without a session")};
g.h.BN=function(){this.fa()?this.Gb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),l8(this,null)):j8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.kz,this),(0,g.x)(this.eL,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.uB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.w("yt.mdx.remote.debug.handlers_")||[],Rqa);g.qf(this.g);i8.bb.U.call(this)};
g.h.Gb=function(a){O7("Controller",a)};
g.h.lz=function(a,b){this.g==a&&(b||l8(this,null),this.M("yt-remote-cast2-session-change",b))};
g.h.DK=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),j8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)j8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{j8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.M("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:l8(this,
new h8(this.i,a));break;case chrome.cast.ReceiverType.DIAL:l8(this,new g8(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:l8(this,new f8(this.i,a));break;default:this.Gb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Gb("Stopping receiver w/o session: "+a.friendlyName)}else this.Gb("onReceiverAction_ called without receiver.")};
g.h.XI=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Gb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return j8("Reselecting dial screen."),
this.M("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);l8(this,new g8(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.lE,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Bq,b))};
g.h.kz=function(a){if(!this.fa()){j8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)j8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),l8(this,new f8(this.i,b),!0);else{this.Gb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=x6(this.i.Qd(),c.label);d&&q6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(j8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new f8(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.lz,this,this.g)),this.g.mi(null));this.g.Ks(a)}}};
g.h.AN=function(){return this.g?this.g.vB():null};
g.h.eL=function(a){this.fa()||(this.Gb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&l8(this,null))};
g.h.HK=function(a){j8("Receiver availability updated: "+a);if(!this.fa()){var b=k8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;k8(this)!=b&&this.M("yt-remote-cast2-availability-change",k8(this))}};
g.h.uB=function(){this.fa()||(this.l=ora(this),j8("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(){this.Gb("Failed to set custom receivers.")},this)),this.M("yt-remote-cast2-availability-change",k8(this)))};
i8.prototype.setLaunchParams=i8.prototype.IM;i8.prototype.setConnectedScreenStatus=i8.prototype.HM;i8.prototype.stopSession=i8.prototype.BN;i8.prototype.getCastSession=i8.prototype.AN;i8.prototype.requestSession=i8.prototype.requestSession;i8.prototype.init=i8.prototype.init;i8.prototype.dispose=i8.prototype.dispose;var r8=[];w8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";x8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ne=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
w8.prototype.isAdPlaying=function(){return 1081==this.playerState};
w8.prototype.getDuration=function(){return this.u?this.D+y8(this):this.D};
w8.prototype.clone=function(){return new w8(C8(this))};g.t(E8,g.N);g.h=E8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,K8(this,"play")):J8(this,"play"),I8(this,1,A8(F8(this))),this.M("remotePlayerChange")):G8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,K8(this,"pause")):J8(this,"pause"),I8(this,2,A8(F8(this))),this.M("remotePlayerChange")):G8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=F8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,K8(this,"seekTo",{newTime:a}))}else J8(this,"seekTo",{newTime:a});I8(this,3,a);this.M("remotePlayerChange")}else G8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,K8(this,"stopVideo")):J8(this,"stopVideo");var a=F8(this);a.index=-1;a.videoId="";x8(a);H8(this,a);this.M("remotePlayerChange")}else G8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=F8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){O7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Gb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){O7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Gb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);J8(this,"setVolume",e)}c.muted=b;c.volume=a;H8(this,c)}else G8(this,g.Qa(this.setVolume,a,b))};
g.h.vA=function(a,b){if(1==this.g){var c=F8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.ec(d,c.g));J8(this,"setSubtitlesTrack",d);H8(this,c)}else G8(this,g.Qa(this.vA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();J8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=F8(this);d.audioTrackId=c;H8(this,d)}else G8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=F8(this);c=c||0;var m={videoId:a,currentIndex:c};B8(l,a,c);g.Ca(b)&&(z8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));J8(this,"setPlaylist",m);d||H8(this,l)};
g.h.Un=function(a,b){if(1==this.g){if(a&&b){var c=F8(this);B8(c,a,b);H8(this,c)}J8(this,"previous")}else G8(this,g.Qa(this.Un,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=F8(this);B8(c,a,b);H8(this,c)}J8(this,"next")}else G8(this,g.Qa(this.nextVideo,a,b))};
g.h.wv=function(){1==this.g?J8(this,"dismissAutoplay"):G8(this,this.wv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.M("proxyStateChange",a,this.g)}g.N.prototype.dispose.call(this)};
g.h.U=function(){Bra(this);this.o=null;this.u.clear();D8(this,null);g.N.prototype.U.call(this)};
g.h.Bt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.M("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.AK=function(a,b){this.M(a,b)};
g.h.BI=function(a){if(!a)this.Ek(null),D8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=F8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)O7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,H8(this,b)}};
g.h.Ek=function(a){O7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Cra(this),this.M("remotePlayerChange")};
g.h.AI=function(a){a?(Cra(this),this.M("remotePlayerChange")):this.Ek(null)};
g.h.gt=function(){J8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.QI=function(){var a=yra();a&&D8(this,a)};
g.h.Gb=function(a){O7("CP",a)};g.t(L8,g.N);g.h=L8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;z8(this.Pa,m);this.o="UNSUPPORTED";M8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,E6())}else M8("Connecting without params"),this.g.connect({},a,E6());Era(this)};
g.h.dispose=function(){this.fa()||(this.M("beforeDispose"),N8(this,3));g.N.prototype.dispose.call(this)};
g.h.U=function(){O8(this);Q8(this);P8(this);g.gq(this.B);this.B=NaN;g.gq(this.D);this.D=NaN;this.l=null;g.ks(this.P);this.P.length=0;this.g.dispose();g.N.prototype.U.call(this);this.o=this.A=this.i=this.Pa=this.g=null};
g.h.BD=function(){this.Oh(2)};
g.h.GI=function(){M8("Channel opened");this.I&&(this.I=!1,P8(this),this.H=g.eq((0,g.x)(function(){M8("Timing out waiting for a screen.");this.Oh(1)},this),15E3));
Bqa(Oqa(this.g),this.N)};
g.h.CI=function(){M8("Channel closed");isNaN(this.u)?H6(!0):H6();this.dispose()};
g.h.DI=function(a){H6();isNaN(this.Kj())?(M8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,M8("Channel error: "+a+" with reconnection in "+this.Kj()+" ms"),N8(this,2))};
g.h.FI=function(a){a.params?M8("Received: action="+a.action+", params="+g.Kg(a.params)):M8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=l6(a.params.devices);this.i=(0,g.ge)(a,function(c){return new o6(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Hra(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Hra(this,!1);break;case "remoteConnected":var b=new o6(l6(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||qqa(this.i,b);
break;case "remoteDisconnected":b=new o6(l6(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Jra(this,a);break;case "nowPlaying":Lra(this,a);break;case "onStateChange":Kra(this,a);break;case "onAdStateChange":Mra(this,a);break;case "onVolumeChanged":Nra(this,a);break;case "onSubtitlesTrackChanged":Ira(this,a);break;case "nowAutoplaying":Ora(this,a);break;case "autoplayDismissed":this.M("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.M("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.M("autoplayModeChange",this.o);"DISABLED"==this.o&&this.M("autoplayDismissed");break;case "onHasPreviousNextChanged":Pra(this,a);break;case "requestAssistedSignIn":this.M("assistedSignInRequested",a.params.authCode);break;default:M8("Unrecognized action: "+a.action)}};
g.h.vM=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&R8(this,"getNowPlaying")}};
g.h.rD=function(){var a=3;this.fa()||(a=0,isNaN(this.Kj())?J7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Oh=function(a){M8("Disconnecting with "+a);O8(this);this.M("beforeDisconnect",a);1==a&&H6();Pqa(this.g,a);this.dispose()};
g.h.qD=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),B8(a,this.l,a.index));return C8(a)};
g.h.JM=function(a){var b=new w8(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.gq(this.B),this.B=g.eq((0,g.x)(this.vM,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&A8(this.Pa)==A8(b)&&g.Kg(this.Pa.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.y)(c,function(d){this.M(d)},this)};
g.h.dw=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Kj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.jD=function(){return this.o||"UNSUPPORTED"};
g.h.kD=function(){return this.A||""};
g.h.tN=function(){if(!isNaN(this.Kj())){var a=this.g.i;g.Eo(a.g);a.start()}};
g.h.CM=function(a,b){R8(this,a,b);Gra(this)};
L8.prototype.subscribe=L8.prototype.subscribe;L8.prototype.unsubscribeByKey=L8.prototype.Mf;L8.prototype.getProxyState=L8.prototype.rD;L8.prototype.disconnect=L8.prototype.Oh;L8.prototype.getPlayerContextData=L8.prototype.qD;L8.prototype.setPlayerContextData=L8.prototype.JM;L8.prototype.getOtherConnectedRemoteId=L8.prototype.dw;L8.prototype.getReconnectTimeout=L8.prototype.Kj;L8.prototype.getAutoplayMode=L8.prototype.jD;L8.prototype.getAutoplayVideoId=L8.prototype.kD;L8.prototype.reconnect=L8.prototype.tN;
L8.prototype.sendMessage=L8.prototype.CM;g.t(S8,S7);g.h=S8.prototype;g.h.Qd=function(a){return this.Yc.$_gs(a)};
g.h.contains=function(a){return!!this.Yc.$_c(a)};
g.h.get=function(a){return this.Yc.$_g(a)};
g.h.start=function(){this.Yc.$_st()};
g.h.add=function(a,b,c){this.Yc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Yc.$_r(a,b,c)};
g.h.Ao=function(a,b,c,d){this.Yc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Yc.$_ubk(this.i[a]);this.i.length=0;this.Yc=null;S7.prototype.U.call(this)};
g.h.xN=function(){this.M("screenChange")};
g.h.fK=function(){this.M("onlineScreenChange")};
a8.prototype.$_st=a8.prototype.start;a8.prototype.$_gspc=a8.prototype.yN;a8.prototype.$_gsppc=a8.prototype.tB;a8.prototype.$_c=a8.prototype.contains;a8.prototype.$_g=a8.prototype.get;a8.prototype.$_a=a8.prototype.add;a8.prototype.$_un=a8.prototype.Ao;a8.prototype.$_r=a8.prototype.remove;a8.prototype.$_gs=a8.prototype.Qd;a8.prototype.$_gos=a8.prototype.sB;a8.prototype.$_s=a8.prototype.subscribe;a8.prototype.$_ubk=a8.prototype.Mf;var k9=null,j9=!1,T8=null,U8=null,i9=null,Y8=[];g.t(l9,g.A);g.h=l9.prototype;
g.h.U=function(){g.A.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.N();this.g.unsubscribe("proxyStateChange",this.hz,this);this.g.unsubscribe("remotePlayerChange",this.Gk,this);this.g.unsubscribe("remoteQueueChange",this.Pn,this);this.g.unsubscribe("autoplayUpNext",this.Ky,this);this.g.unsubscribe("previousNextChange",this.ez,this);this.g.unsubscribe("nowAutoplaying",this.az,this);this.g.unsubscribe("autoplayDismissed",this.Jy,this);this.g=this.u=null};
g.h.Gx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(o9(this)){if(!F8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==F8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Rj(c[0],c[1]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();q9(this,0==c?void 0:c);break;case "control_seek":q9(this,c[0]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.zI=function(a){this.I.xD(a)};
g.h.dN=function(a){this.Gx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.GA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||p9(this,a)};
g.h.Vy=function(a){if(o9(this)){this.g.unsubscribe("remotePlayerChange",this.Gk,this);var b=Math.round(a.volume);a=!!a.muted;var c=F8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Gk,this)}};
g.h.AJ=function(){g.Xb(this.B)||asa(this,this.B);this.D=!1};
g.h.hz=function(a,b){this.A.stop();2==b&&this.FA()};
g.h.Gk=function(){if(o9(this)){this.o.stop();var a=F8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Um=1;break;case 1082:case 1083:this.u.Um=0;break;default:this.u.Um=-1}switch(a.playerState){case 1081:case 1:n9(this,new g.OC(8));this.EA();break;case 1085:case 3:n9(this,new g.OC(9));break;case 1083:case 0:n9(this,new g.OC(2));this.H.stop();m9(this,this.i.getVideoData().lengthSeconds);break;case 1084:n9(this,new g.OC(4));break;case 2:n9(this,new g.OC(4));m9(this,A8(a));
break;case -1:n9(this,new g.OC(64));break;case -1E3:n9(this,new g.OC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=F8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,asa(this,a));a=F8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.gB()}else $ra(this)};
g.h.ez=function(){this.i.M("mdxpreviousnextchange")};
g.h.Pn=function(){o9(this)||$ra(this)};
g.h.EC=function(){this.g.wv()};
g.h.Ky=function(a){a&&(a=g.br("/watch_queue_ajax",{method:"GET",td:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.GL,this)}))&&(this.N=(0,g.x)(a.abort,a))};
g.h.GL=function(a,b){var c=new g.yB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.M("mdxautoplayupnext",c)};
g.h.az=function(a){isNaN(a)||this.i.M("mdxnowautoplaying",a)};
g.h.Jy=function(){this.i.M("mdxautoplaycanceled")};
g.h.XF=function(a,b){-1==F8(this.g).playerState?q9(this,a):b&&this.g.seekTo(a)};
g.h.gB=function(){if(o9(this)){var a=F8(this.g);this.l.Na(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.K(this.i,"onVolumeChange",this.Vy)}};
g.h.EA=function(){this.o.stop();if(!this.g.fa()){var a=F8(this.g);1==a.playerState&&n9(this,new g.OC(8));m9(this,A8(a));this.o.start()}};
g.h.FA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(r9,g.W);r9.prototype.o=function(){n6("mdx-privacy-popup-cancel");this.l.hide()};
r9.prototype.A=function(){n6("mdx-privacy-popup-confirm");this.l.hide()};g.t(s9,g.W);s9.prototype.u=function(a){csa(this,a.state)};g.t(t9,g.nU);t9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.B=g.tb(a,this.A,this),g.pU(this,(0,g.ge)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.le(this.A(a)),this.enable(!0)):this.enable(!1)};
t9.prototype.A=function(a){return a.key};
t9.prototype.ye=function(a){return"cast-selector-receiver"==a?"Cast...":this.B[a].name};
t9.prototype.Lc=function(a){g.nU.prototype.Lc.call(this,a);this.l.setOption("remote","currentReceiver",this.B[a]);this.o.nb()};g.t(u9,g.iL);g.h=u9.prototype;
g.h.create=function(){Ura(g.dz(g.X(this.player)));this.o.push(g.lq("yt-remote-before-disconnect",this.wI,this));this.o.push(g.lq("yt-remote-connection-change",this.IK,this));this.o.push(g.lq("yt-remote-receiver-availability-change",this.fz,this));this.o.push(g.lq("yt-remote-auto-connect",this.GK,this));this.o.push(g.lq("yt-remote-receiver-resumed",this.FK,this));this.o.push(g.lq("mdx-privacy-popup-confirm",this.lM,this));this.o.push(g.lq("mdx-privacy-popup-cancel",this.kM,this));this.fz()};
g.h.load=function(){this.player.cancelPlayback();g.iL.prototype.load.call(this);this.u=new l9(this,this.player,this.g);var a=(a=Zra())?a.currentTime:0;var b=h9()?new E8(c9(),void 0):null;0==a&&b&&(a=A8(F8(b)));0!=a&&this.Nc(a);bsa(this,this.pk,this.pk);g.qY(this.player.app,6)};
g.h.unload=function(){this.player.M("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.iL.prototype.unload.call(this);g.qY(this.player.app,5);v9(this)};
g.h.U=function(){g.mq(this.o);g.iL.prototype.U.call(this)};
g.h.af=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Gx.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Um};
g.h.tD=function(){return this.loaded?this.u.suggestion:null};
g.h.Ne=function(){return this.g?F8(this.g).Ne:!1};
g.h.hasNext=function(){return this.g?F8(this.g).hasNext:!1};
g.h.Nc=function(a,b){this.I=a||0;this.player.M("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.I};
g.h.getProgressState=function(){var a=F8(this.g),b=this.player.getVideoData();return{allowSeeking:g.O(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ec():!a.isAdPlaying()&&this.player.ec(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+y8(a):a.l,isAtLiveHead:1>=(a.u?a.i+y8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+y8(a):a.i,seekableStart:0<a.o?a.o+
y8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Un=function(){this.g&&this.g.Un()};
g.h.wI=function(a){1==a&&(this.F=this.g?F8(this.g):null)};
g.h.IK=function(){var a=h9()?new E8(c9(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.F=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.F)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,A8(a)));this.player.M("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.fz=function(){this.B=[this.i].concat(Wra());var a=d9()||this.i;w9(this,a);this.player.la("onMdxReceiversChange")};
g.h.fM=function(a){!this.D&&g.$D(a,8)&&(this.player.pauseVideo(),v9(this))};
g.h.GK=function(){var a=d9();w9(this,a)};
g.h.FK=function(){this.l=d9()};
g.h.lM=function(){this.D=!0;v9(this);j9=!1;k9&&f9(k9,1);k9=null};
g.h.kM=function(){this.D=!1;v9(this);w9(this,this.i);this.l=this.i;j9=!1;k9=null;this.player.playVideo()};
g.h.zc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.B;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?u8():w9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.B.length&&"cast-selector-receiver"==this.B[1].key?(b&&u8(),!0):!1}};
g.h.gt=function(){this.g.gt()};
g.h.Nb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.EV.remote=u9;})(_yt_player);
